#!/usr/bin/env python3
"""Ingest text, Markdown, and optional PDF sources into the wiki."""

from __future__ import annotations

from datetime import date
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
RAW_TEXT = ROOT / "raw" / "sources" / "text"
RAW_PDF = ROOT / "raw" / "sources" / "pdf"
WIKI_SOURCES = ROOT / "wiki" / "sources"
INDEX = ROOT / "wiki" / "index.md"
LOG = ROOT / "wiki" / "log.md"


def slugify(value: str) -> str:
    stem = Path(value).stem.lower()
    stem = re.sub(r"[^a-z0-9가-힣]+", "-", stem).strip("-")
    return stem or "source"


def today() -> str:
    return date.today().isoformat()


def read_pdf_text(path: Path) -> str:
    try:
        from pypdf import PdfReader
    except ImportError as exc:
        raise SystemExit(
            "PDF ingest requires pypdf. Install it with: python3 -m pip install pypdf"
        ) from exc
    reader = PdfReader(str(path))
    chunks = []
    for index, page in enumerate(reader.pages, start=1):
        chunks.append(f"\n\n<!-- page: {index} -->\n\n{page.extract_text() or ''}")
    return "\n".join(chunks).strip() + "\n"


def ensure_dirs() -> None:
    RAW_TEXT.mkdir(parents=True, exist_ok=True)
    RAW_PDF.mkdir(parents=True, exist_ok=True)
    WIKI_SOURCES.mkdir(parents=True, exist_ok=True)
    (ROOT / "wiki" / "maintenance").mkdir(parents=True, exist_ok=True)


def source_frontmatter(raw_rel: str) -> str:
    day = today()
    return (
        "---\n"
        "type: source\n"
        "status: stable\n"
        f"created: {day}\n"
        f"updated: {day}\n"
        "sources:\n"
        f"  - ../../{raw_rel}\n"
        "related:\n"
        "  - ../concepts/wiki-harness.md\n"
        "---\n\n"
    )


def source_summary(text: str) -> list[str]:
    lines = [line.strip("# \t") for line in text.splitlines() if line.strip()]
    summary = lines[:4]
    while len(summary) < 4:
        summary.append("Review this source and promote important ideas into concept pages.")
    return summary


def write_source_page(raw_path: Path, text: str) -> Path:
    slug = slugify(raw_path.name)
    out = WIKI_SOURCES / f"{slug}.md"
    raw_rel = raw_path.relative_to(ROOT).as_posix()
    bullets = "\n".join(f"- {item[:180]}" for item in source_summary(text))
    out.write_text(
        source_frontmatter(raw_rel)
        + f"# {slug}\n\n"
        + "## Summary\n\n"
        + f"Source page generated from `{raw_rel}`.\n\n"
        + "## Key Points\n\n"
        + bullets
        + "\n\n## Details\n\n"
        + "Use this page as the stable wiki-facing reference for the raw source snapshot.\n\n"
        + "## Source Notes\n\n"
        + f"- Raw source: `{raw_rel}`\n\n"
        + "## Open Questions\n\n"
        + "- Which concepts should be promoted from this source?\n\n"
        + "## Maintenance Notes\n\n"
        + "- Generated by `scripts/ingest_sources.py`.\n",
        encoding="utf-8",
    )
    return out


def collect_sources() -> list[tuple[Path, str]]:
    sources: list[tuple[Path, str]] = []
    for path in sorted(RAW_TEXT.glob("*")):
        if path.suffix.lower() in {".md", ".txt"} and path.is_file():
            sources.append((path, path.read_text(encoding="utf-8", errors="ignore")))
    for path in sorted(RAW_PDF.glob("*.pdf")):
        text_path = RAW_TEXT / f"{slugify(path.name)}.md"
        text = read_pdf_text(path)
        text_path.write_text(f"# Text Snapshot: {path.stem}\n\n{text}", encoding="utf-8")
        sources.append((text_path, text_path.read_text(encoding="utf-8", errors="ignore")))
    return sources


def rebuild_index(source_pages: list[Path]) -> None:
    day = today()
    links = "\n".join(
        f"- [{path.stem}](sources/{path.name})" for path in sorted(source_pages)
    )
    INDEX.write_text(
        "---\n"
        "type: index\n"
        "status: stable\n"
        f"created: {day}\n"
        f"updated: {day}\n"
        "sources:\n"
        "  - ../AGENTS.md\n"
        "related:\n"
        "  - concepts/wiki-harness.md\n"
        "  - workflows/source-to-wiki.md\n"
        "---\n\n"
        "# LLM Wiki Index\n\n"
        "## Summary\n\n"
        "Entry point for the local Markdown-only LLM Wiki.\n\n"
        "## Start Here\n\n"
        "- [Wiki Harness](concepts/wiki-harness.md)\n"
        "- [Source To Wiki Workflow](workflows/source-to-wiki.md)\n"
        "- [Example Query](queries/example-query.md)\n\n"
        "## Source Pages\n\n"
        + (links or "- No source pages yet.")
        + "\n\n## Maintenance\n\n"
        "- [Latest Maintenance Report](maintenance/latest-maintenance-report.md)\n"
        "- [Wiki Graph](maintenance/wiki-graph.md)\n"
        "- [Operation Log](log.md)\n",
        encoding="utf-8",
    )


def append_log(count: int) -> None:
    day = today()
    if not LOG.exists():
        LOG.write_text(
            "---\ntype: log\nstatus: stable\n"
            f"created: {day}\nupdated: {day}\n"
            "sources:\n  - ../AGENTS.md\nrelated:\n  - index.md\n---\n\n# Operation Log\n",
            encoding="utf-8",
        )
    existing = LOG.read_text(encoding="utf-8", errors="ignore").rstrip()
    LOG.write_text(
        existing
        + f"\n\n## {day} - ingest_sources.py\n"
        + f"- Refreshed {count} source pages from raw source snapshots.\n",
        encoding="utf-8",
    )


def main() -> int:
    ensure_dirs()
    sources = collect_sources()
    if not sources:
        print("No sources found. Add .md or .txt files to raw/sources/text/.")
        return 1
    pages = [write_source_page(path, text) for path, text in sources]
    rebuild_index(pages)
    append_log(len(pages))
    print(f"Ingested {len(pages)} source snapshot(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

